const grammarData = [
    {
        id: 1,
        title: "Basic English",
        subtitle: "Alphabet, Vowels, Consonants, Sentence Structure",
        icon: "🔤",
        color: "#0077b6",
        rules: [
            { word: "Alphabet", desc: "English ma 26 letters chhe", gujarati: "અંગ્રેજીમાં ૨૬ અક્ષરો છે", example: "a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z", exampleGujarati: "એ, બી, સી, ડી, ઈ, એફ, જી, એચ, આઈ, જે, કે, એલ, એમ, એન, ઓ, પી, ક્યુ, આર, એસ, ટી, યુ, વી, ડબલ્યુ, એક્સ, વાય, ઝેડ" },
            { word: "Vowels (સ્વર)", desc: "5 vowels chhe", gujarati: "૫ સ્વર છે — a, e, i, o, u", example: "a, e, i, o, u", exampleGujarati: "એ, ઈ, આઈ, ઓ, યુ" },
            { word: "Consonants (વ્યંજન)", desc: "21 consonants chhe", gujarati: "૨૧ વ્યંજન છે", example: "b, c, d, f, g, h, j, k, l, m, n, p, q, r, s, t, v, w, x, y, z", exampleGujarati: "બી, સી, ડી, એફ, જી, એચ, જે, કે, એલ, એમ, એન, પી, ક્યુ, આર, એસ, ટી, વી, ડબલ્યુ, એક્સ, વાય, ઝેડ" },
            { word: "Semi-vowel (અર્ધ-સ્વર)", desc: "'y' semi-vowel chhe", gujarati: "'y' અર્ધ-સ્વર છે — ક્યારેક સ્વર, ક્યારેક વ્યંજન", example: "Yellow (consonant sound), Cry (vowel sound)", exampleGujarati: "યેલો (વ્યંજન ઉચ્ચાર), ક્રાય (સ્વર ઉચ્ચાર)" },
            { word: "General Structure", desc: "Subject + Helping Verb + Main Verb + Object + Other Words", gujarati: "કર્તા + સહાયક ક્રિયાપદ + મુખ્ય ક્રિયાપદ + કર્મ + અન્ય શબ્દો", example: "Vijay sir teaches English.", exampleGujarati: "વિજય સર અંગ્રેજી ભણાવે છે." },
            { word: "Subject (કર્તા)", desc: "Je kriya kare", gujarati: "જેના દ્વારા ક્રિયા થતી હોય તેને કર્તા કહેવાય", example: "Dhruvi is buying a new book. (Dhruvi = Subject)", exampleGujarati: "ધ્રુવી એક નવું પુસ્તક ખરીદી રહી છે. (ધ્રુવી = કર્તા)" },
            { word: "Helping Verb", desc: "am/is/are, was/were, will/shall, have/has/had, do/does/did, can/could/may/should/would", gujarati: "આ સહાયક ક્રિયાપદ છે", example: "is, was, will, have, do, can", exampleGujarati: "છે, હતું, હશે, પાસે, કરવું, શકવું" },
            { word: "Main Verb (મુખ્ય ક્રિયાપદ)", desc: "Action word", gujarati: "મુખ્ય ક્રિયાપદ — રમવું, ખાવું, પીવું, દોડવું, ખરીદવું", example: "buying, eating, drinking, running, playing", exampleGujarati: "ખરીદવું, ખાવું, પીવું, દોડવું, રમવું" },
            { word: "Object (કર્મ)", desc: "Jena par kriya thay", gujarati: "જેના પર ક્રિયા થતી હોય તેને કર્મ કહેવાય", example: "Dhruvi is buying a new book. (book = Object)", exampleGujarati: "ધ્રુવી એક નવું પુસ્તક ખરીદી રહી છે. (પુસ્તક = કર્મ)" },
            { word: "Other Words (અન્ય શબ્દો)", desc: "Vakya ma vadharana shabdo", gujarati: "વાક્યમાં વધારાના શબ્દોને અન્ય શબ્દો તરીકે ઓળખવામાં આવે છે", example: "Dhruvi is buying a new book now. (now = Other word)", exampleGujarati: "ધ્રુવી એક નવું પુસ્તક ખરીદી રહી છે. (હવે = અન્ય શબ્દ)" },
            { word: "Structure (વાક્યરચના)", desc: "S + H.V. + M.V. + O + O.W.", gujarati: "કર્તા + સહાયક ક્રિયાપદ + મુખ્ય ક્રિયાપદ + કર્મ + અન્ય શબ્દો", example: "| Sub. | + H.V. | + M.V. | + Obj. | + O.W. |", exampleGujarati: "| કર્તા | + સહાયક | + મુખ્ય | + કર્મ | + અન્ય |" },
            { word: "Vakya ma badlav", desc: "Kayi vakhat vakya ma ferfar thay", gujarati: "કઈ વખત વાક્યમાં ફેરફાર થાય — ત્યારે helping verb ane main verb badlay", example: "I am eating. / He is eating. / They are eating.", exampleGujarati: "હું ખાઈ રહ્યો છું. / તે ખાઈ રહ્યો છે. / તેઓ ખાઈ રહ્યા છે." },
            { word: "Subject na prakar", desc: "Subject ekvachan ke bahuvachan hoy", gujarati: "કર્તા એકવચન કે બહુવચન હોય", example: "He is a boy. / They are boys.", exampleGujarati: "તે એક છોકરો છે. / તેઓ છોકરાઓ છે." },
            { word: "Object na prakar", desc: "Object ekvachan ke bahuvachan hoy", gujarati: "કર્મ એકવચન કે બહુવચન હોય", example: "I have a book. / I have books.", exampleGujarati: "મારી પાસે એક પુસ્તક છે. / મારી પાસે પુસ્તકો છે." },
            { word: "Vakya na prakar", desc: "Affirmative, Negative, Interrogative", gujarati: "હકાર, નકાર, પ્રશ્ન", example: "I am a doctor. / I am not a doctor. / Am I a doctor?", exampleGujarati: "હું ડોક્ટર છું. / હું ડોક્ટર નથી. / શું હું ડોક્ટર છું?" }
        ],
        structure: [
            "| Subject (કર્તા) | + Helping Verb (સહાયક) | + Main Verb (મુખ્ય) | + Object (કર્મ) | + Other Words (અન્ય) |",
            "| Sub. (S) | + H.V. | + M.V. | + Obj. (O) | + O.W. |",
            "Example: Vijay sir teaches English.",
            "Example: Dhruvi is buying a new book now.",
            "Example: I am eating food.",
            "Example: He is playing cricket."
        ],
        tips: [
            "💡 English vakya ma **Subject + Verb + Object** no order hamesha rakhvo",
            "💡 Gujarati ma order badlai shake, pan English ma nahi",
            "💡 'Dhruvi is buying a new book' — aa sentence ma badha parts chhe",
            "💡 Kayi vakhat vakya ma Subject na hoy, tyare 'There' vaparay",
            "💡 English ma 26 letters, 5 vowels, 21 consonants chhe",
            "💡 'y' semi-vowel chhe — kayi vakhat vowel, kayi vakhat consonant",
            "💡 Vakya na 3 prakar: Affirmative, Negative, Interrogative",
            "💡 Helping verb vakya ma ferfar pramane badlay chhe",
            "💡 Main verb hamesha action darshavे chhe",
            "💡 Object hamesha main verb pachi aave chhe"
        ],
        commonMistakes: [
            "❌ Vijay sir English teaches. (ખોટું — ગુજરાતી order)",
            "✅ Vijay sir teaches English. (સાચું — English order)",
            "❌ English Vijay sir teaches. (ખોટું)",
            "✅ Vijay sir teaches English. (સાચું)",
            "❌ Teaches Vijay sir English. (ખોટું)",
            "✅ Vijay sir teaches English. (સાચું)",
            "❌ I is a doctor. (ખોટું)",
            "✅ I am a doctor. (સાચું)",
            "❌ He are a boy. (ખોટું)",
            "✅ He is a boy. (સાચું)"
        ],
        practice: [
            { q: "How many letters in English alphabet?", a: "26", gujarati: "અંગ્રેજીમાં ૨૬ અક્ષરો છે" },
            { q: "How many vowels are there?", a: "5", gujarati: "૫ સ્વર છે" },
            { q: "How many consonants are there?", a: "21", gujarati: "૨૧ વ્યંજન છે" },
            { q: "Which letter is semi-vowel?", a: "y", gujarati: "'y' અર્ધ-સ્વર છે" },
            { q: "In 'Dhruvi is buying a book', who is subject?", a: "Dhruvi", gujarati: "ધ્રુવી કર્તા છે" },
            { q: "In 'Dhruvi is buying a book', what is object?", a: "book", gujarati: "પુસ્તક કર્મ છે" },
            { q: "In 'Dhruvi is buying a book', what is 'is'?", a: "Helping verb", gujarati: "'is' સહાયક ક્રિયાપદ છે" },
            { q: "In 'Dhruvi is buying a book', what is 'buying'?", a: "Main verb", gujarati: "'buying' મુખ્ય ક્રિયાપદ છે" },
            { q: "In 'Dhruvi is buying a book', what is 'now'?", a: "Other word", gujarati: "'now' અન્ય શબ્દ છે" },
            { q: "What is the structure of English sentence?", a: "Subject + Verb + Object", gujarati: "કર્તા + ક્રિયાપદ + કર્મ" },
            { q: "Vowels na letters kaya chhe?", a: "a, e, i, o, u", gujarati: "સ્વરના અક્ષરો" },
            { q: "Consonants na letters kaya chhe?", a: "b, c, d, f, g, h, j, k, l, m, n, p, q, r, s, t, v, w, x, y, z", gujarati: "વ્યંજનના અક્ષરો" },
            { q: "Vakya na ketla prakar chhe?", a: "3", gujarati: "ત્રણ — હકાર, નકાર, પ્રશ્ન" },
            { q: "Affirmative vakya nu udaharan?", a: "I am a doctor.", gujarati: "હું ડોક્ટર છું." },
            { q: "Negative vakya nu udaharan?", a: "I am not a doctor.", gujarati: "હું ડોક્ટર નથી." },
            { q: "Interrogative vakya nu udaharan?", a: "Am I a doctor?", gujarati: "શું હું ડોક્ટર છું?" }
        ],
        quiz: [
            { q: "How many letters in English alphabet?", options: ["24", "25", "26", "27"], answer: "26" },
            { q: "How many vowels are there?", options: ["3", "4", "5", "6"], answer: "5" },
            { q: "How many consonants are there?", options: ["20", "21", "22", "23"], answer: "21" },
            { q: "Which letter is semi-vowel?", options: ["a", "e", "y", "o"], answer: "y" },
            { q: "In 'Dhruvi is buying a book', what is 'is'?", options: ["Main verb", "Helping verb", "Object", "Subject"], answer: "Helping verb" },
            { q: "In 'Dhruvi is buying a book', what is 'buying'?", options: ["Main verb", "Helping verb", "Object", "Subject"], answer: "Main verb" },
            { q: "In 'Dhruvi is buying a book', what is 'book'?", options: ["Main verb", "Helping verb", "Object", "Subject"], answer: "Object" },
            { q: "In 'Dhruvi is buying a book', what is 'Dhruvi'?", options: ["Main verb", "Helping verb", "Object", "Subject"], answer: "Subject" },
            { q: "In 'Dhruvi is buying a book now', what is 'now'?", options: ["Main verb", "Other word", "Object", "Subject"], answer: "Other word" },
            { q: "What is the structure of English sentence?", options: ["S+V+O", "V+S+O", "O+S+V", "S+O+V"], answer: "S+V+O" },
            { q: "Which of these is a vowel?", options: ["b", "c", "e", "d"], answer: "e" },
            { q: "Which of these is a consonant?", options: ["a", "b", "e", "i"], answer: "b" },
            { q: "Vakya na ketla prakar chhe?", options: ["2", "3", "4", "5"], answer: "3" },
            { q: "Affirmative vakya nu udaharan?", options: ["I am a doctor.", "I am not a doctor.", "Am I a doctor?", "None"], answer: "I am a doctor." },
            { q: "Negative vakya nu udaharan?", options: ["I am a doctor.", "I am not a doctor.", "Am I a doctor?", "None"], answer: "I am not a doctor." },
            { q: "Interrogative vakya nu udaharan?", options: ["I am a doctor.", "I am not a doctor.", "Am I a doctor?", "None"], answer: "Am I a doctor?" }
        ]
    }
];